import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { motion as m } from 'framer-motion';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <m.div
      initial={{ y: '100%' }}
      animate={{ y: '0%' }}
      transition={{ duration: 0.75, ease: 'easeOut' }}
      exit={{ opacity: 1 }}
      className='text-gray-900 absolute top-0 left-0 w-full h-full bg-orange-200 px-16'
    >
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='my-96 p-1'>
          <h1 className='text-6xl text-center lg:text-right lg:text-9xl'>
            Happy Pickle
          </h1>
        </div>
        <div className='flex justify-between '>
          <div>
            <h2>Design</h2>
            <h2>Company</h2>
            <h2>2022</h2>
          </div>
          <div>
            <h3>Pickle that makes you smile.</h3>
            <h2>Scottish designs to make you happy.</h2>
            <h2>Cick contact for cool transition.</h2>
          </div>
        </div>
      </main>
    </m.div>
  );
}
